### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lsl13541588428** [xiaoandx/learningCode#3]
@xiaoandx 
in huffmanTree stringToWeight() There are running bugs is 3221225477。

### Problem arrangement：
3221225477 (0xC0000005): 访问越界，一般是读或写了野指针指向的内存
3221225725 (0xC00000FD): 堆栈溢出，一般是无穷递归造成的
3221225620 (0xC0000094): 除0错误，一般发生在整型数据除了0的时候

**Comment by xiaoandx** [comment]
OK，update successfully. 
Modified to solve the problem of complete wild pointer
`int* countArrayS;`
`countArrayS = (int*)malloc(INIT_SIZE * sizeof(int));`

**Comment by thevestor** [comment]
debug:#define 自定义命名，占编译时间。

**Comment by xiaoandx** [comment]
thinks ，but not why

**Comment by xiaoandx** [comment]
@thevestor  thinks

define 编译确实会占用时间，但是可以节省空间等，利大于弊
